const CAST_ERROR_CODE = 400;
const NOTFOUND_ERROR_CODE = 404;
const DUPLICATE_ERROR_CODE = 409;
const DEFAULT_ERROR_CODE = 500;

module.exports = {
  CAST_ERROR_CODE,
  NOTFOUND_ERROR_CODE,
  DEFAULT_ERROR_CODE,
  DUPLICATE_ERROR_CODE,
};
